FROM silex/emacs:30

RUN apt-get update && apt-get install -y --no-install-recommends git python3-poetry-plugin-export python3-venv tini && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY pyproject.toml poetry.lock /src/
RUN poetry export > requirements.txt

RUN python3 -m venv /venv
ENV VIRTUAL_ENV=/venv
ENV PATH=/venv/bin:$PATH
RUN pip3 install -r requirements.txt

ENV GIT_ADVICE=0

RUN rm -rf /src
